freshrss-passwd: ENC[AES256_GCM,data:mUMYJgVWzuS/psnSdxqh/Ea10sAKXNv9TVESDO4xGg==,iv:z0m0VEUCXFwraGcfAhs9RMMdyJUrrCR14BVo3oUonUY=,tag:WBrxa50mjQyeeHZjiX/zyw==,type:str]
wireguard-private-key: ENC[AES256_GCM,data:/1vB72WCfBWqLit6ojBiDmCUQINWKcwAjzb0dlAzrdVZWz1MUOhmJZ5cpbw=,iv:KIjwjkvZr0ICT5MfdDXqvFt22wwnXL1EF5n1vxGDwaI=,tag:8+NyEy20Qkun2hPm+UyrFw==,type:str]
sops:
    age:
        - recipient: age1d9kjeae072xl0uhly9y80wq4ayznxxen6kkpv042dp6pg3ta35msve4qhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOUlSV0kwNHV3U3djSmtn
            c0JaalpNSUE2R015TEhWRW8vMGNYdlBXVWhjCm1UYWFiY0pqMFJUMlZKRldpQTBs
            WjNEWENrN0VLZGZBZDJDMXVkSmZzaXcKLS0tIDN3Mm5pWmlKWndXaEFvVUxzTWRw
            amdqczlDMVhZbkxFWU9sblVON2dsSXcKsqkNKdqN/IcY2ONTfP9OxVyASk1zQRBW
            BoHOg7usp0fkhq1xdWSk5yyLD9aGiBw3XdI4xJKTbBoIJs1HK/VRCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-05T21:32:36Z"
    mac: ENC[AES256_GCM,data:SdnYSsrEx2SnppHFuuhLrO5g4WWahwDP5rLuwpHJCdoLPDfjgzE4Wo9JnhkxZmkg/ppkW5cFxLf6pFGADTdDdrp3bUrJouOfno8lhyrtqQjdVe0EorrAFkuwaovFxGJ1C4i6+rUeg3sZ7oN+xZ6TI96HmjH0B2Cbr6U1cGDEtUs=,iv:J0OtUKrPrnxrCnLN7l5qkm20dvC3APJlKz+C0HDAbz8=,tag:qEv2Krrl6W4dXyKlyuTyMw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
